print('-----> methods<-----')
texto = '  helloWorld My name is Ulises  '
print(texto.upper())
print(texto.lower())
print(texto.title())
print(texto.capitalize())
print(texto.swapcase())
print(texto.strip())
print(texto.lstrip())
print(texto.rstrip())
print('helloWorld'.strip('hello'))
print('uno-dos-tres')
print('uno-dos-tres')
print('uno-dos-tres')
print('uno-dos-tres')
print('uno-dos-tres')